theme: jekyll-theme-minimal
title: Kori's Homepage
description: For Professional Development, I have decided to complete a series of LinkedIn training courses to improve some of my soft skills, including teamwork, communication, and leadership, among others. Keep an eye on this page for updates on my progress.
